const majorArcana = [
  ['The Fool', 'Khởi đầu mới, niềm tin, bước nhảy vào điều chưa biết.', 'Thiếu chuẩn bị, bốc đồng, cần nhìn lại rủi ro.'],
  ['The Magician', 'Ý chí, kỹ năng, khả năng biến ý tưởng thành hành động.', 'Năng lượng phân tán, thao túng, chưa dùng đúng năng lực.'],
  ['The High Priestess', 'Trực giác, bí mật, sự lắng nghe bên trong.', 'Bỏ qua trực giác, điều bị che giấu, nhiễu loạn cảm xúc.'],
  ['The Empress', 'Nuôi dưỡng, sáng tạo, tình yêu và sự sinh sôi.', 'Phụ thuộc, thiếu chăm sóc bản thân, sáng tạo bị kẹt.'],
  ['The Emperor', 'Kỷ luật, nền tảng, quyền lực và cấu trúc.', 'Cứng nhắc, kiểm soát quá mức, thiếu linh hoạt.'],
  ['The Hierophant', 'Truyền thống, niềm tin, học hỏi từ hệ thống.', 'Phá khuôn, nghi ngờ niềm tin cũ, cần tự tìm chân lý.'],
  ['The Lovers', 'Lựa chọn từ trái tim, kết nối, hòa hợp giá trị.', 'Lệch giá trị, do dự, lựa chọn thiếu thành thật.'],
  ['The Chariot', 'Tiến lên, kiểm soát hướng đi, chiến thắng nhờ tập trung.', 'Mất hướng, nóng vội, kéo nhau bởi nhiều lực trái chiều.'],
  ['Strength', 'Can đảm mềm mại, tự chủ, sức mạnh nội tâm.', 'Thiếu tự tin, phản ứng bản năng, cần kiên nhẫn hơn.'],
  ['The Hermit', 'Tĩnh lặng, chiêm nghiệm, tìm câu trả lời bên trong.', 'Cô lập, né tránh, khó mở lòng nhận hỗ trợ.'],
  ['Wheel of Fortune', 'Chu kỳ đổi vận, cơ hội, bước ngoặt định mệnh.', 'Kháng cự thay đổi, vòng lặp cũ, thời điểm chưa chín.'],
  ['Justice', 'Sự thật, cân bằng, trách nhiệm và hệ quả.', 'Thiên lệch, né trách nhiệm, quyết định thiếu công bằng.'],
  ['The Hanged Man', 'Tạm dừng, đổi góc nhìn, buông kiểm soát.', 'Mắc kẹt vì trì hoãn, hy sinh không cần thiết.'],
  ['Death', 'Kết thúc để tái sinh, chuyển hóa sâu sắc.', 'Sợ buông bỏ, níu kéo điều đã hết vai trò.'],
  ['Temperance', 'Điều độ, chữa lành, phối hợp hài hòa.', 'Mất cân bằng, cực đoan, cần tiết chế.'],
  ['The Devil', 'Ràng buộc, ham muốn, thói quen hoặc nỗi sợ chi phối.', 'Nhận ra xiềng xích, cơ hội giải phóng bản thân.'],
  ['The Tower', 'Đổ vỡ bất ngờ, sự thật phá vỡ cấu trúc cũ.', 'Tránh né biến động, cảnh báo cần thay đổi trước khi quá muộn.'],
  ['The Star', 'Hy vọng, hồi phục, niềm tin vào tương lai.', 'Mất niềm tin, cần chăm lại nguồn cảm hứng.'],
  ['The Moon', 'Mơ hồ, tiềm thức, nỗi sợ và điều chưa rõ.', 'Sự thật dần lộ diện, bớt hoang mang.'],
  ['The Sun', 'Rõ ràng, vui sống, thành công và năng lượng tích cực.', 'Niềm vui bị che mờ, tự tin chưa trọn vẹn.'],
  ['Judgement', 'Thức tỉnh, tiếng gọi mới, nhìn lại để bước tiếp.', 'Chưa tha thứ cho mình, trì hoãn quyết định lớn.'],
  ['The World', 'Hoàn tất chu kỳ, thành tựu, hội nhập và mở rộng.', 'Còn dang dở, thiếu bước kết thúc rõ ràng.'],
];

const majorVietnameseNames = [
  'Kẻ Khờ',
  'Nhà Ảo Thuật',
  'Nữ Tư Tế',
  'Hoàng Hậu',
  'Hoàng Đế',
  'Giáo Hoàng',
  'Tình Nhân',
  'Cỗ Xe',
  'Sức Mạnh',
  'Ẩn Sĩ',
  'Bánh Xe Số Mệnh',
  'Công Lý',
  'Người Treo Ngược',
  'Cái Chết',
  'Tiết Độ',
  'Ác Quỷ',
  'Tòa Tháp',
  'Ngôi Sao',
  'Mặt Trăng',
  'Mặt Trời',
  'Phán Xét',
  'Thế Giới',
];

const minorRankVietnamese = [
  'Át',
  'Hai',
  'Ba',
  'Bốn',
  'Năm',
  'Sáu',
  'Bảy',
  'Tám',
  'Chín',
  'Mười',
  'Tiểu đồng',
  'Kỵ sĩ',
  'Nữ hoàng',
  'Vua',
];

const suits = [
  {
    name: 'Wands',
    vi: 'Gậy',
    theme: 'đam mê, hành động, cảm hứng và tham vọng',
    cards: [
      ['Ace of Wands', 'Tia lửa mới, động lực, cơ hội bắt đầu mạnh mẽ.', 'Ý tưởng chưa được kích hoạt, thiếu lửa hoặc ngại bắt đầu.'],
      ['Two of Wands', 'Lập kế hoạch, nhìn xa, chuẩn bị mở rộng.', 'Do dự, sợ bước ra vùng quen thuộc.'],
      ['Three of Wands', 'Chờ kết quả, mở rộng tầm nhìn, cơ hội xa hơn.', 'Chậm tiến triển, kế hoạch cần điều chỉnh.'],
      ['Four of Wands', 'Ăn mừng, ổn định, nền tảng vui vẻ.', 'Niềm vui trì hoãn, thiếu cảm giác thuộc về.'],
      ['Five of Wands', 'Cạnh tranh, va chạm, thử sức.', 'Tránh xung đột hoặc xung đột âm ỉ chưa xử lý.'],
      ['Six of Wands', 'Được công nhận, chiến thắng, tiến bộ rõ ràng.', 'Thiếu ghi nhận, tự nghi ngờ, thành công chưa chắc.'],
      ['Seven of Wands', 'Bảo vệ lập trường, giữ vị thế.', 'Mệt vì phòng thủ, cần chọn trận đáng đánh.'],
      ['Eight of Wands', 'Tin nhanh, chuyển động nhanh, tiến triển dồn dập.', 'Trì hoãn, nhiễu thông tin, tốc độ không đều.'],
      ['Nine of Wands', 'Bền bỉ, cảnh giác, gần đến đích.', 'Kiệt sức, phòng vệ quá mức.'],
      ['Ten of Wands', 'Gánh nặng, trách nhiệm lớn, quá tải.', 'Buông bớt, chia việc, kết thúc giai đoạn nặng.'],
      ['Page of Wands', 'Tin mới, tò mò, khởi động hành trình sáng tạo.', 'Nhiệt hứng thất thường, thiếu cam kết.'],
      ['Knight of Wands', 'Hành động nhanh, đam mê, phiêu lưu.', 'Nóng vội, thiếu kế hoạch, dễ bốc đồng.'],
      ['Queen of Wands', 'Tự tin, cuốn hút, độc lập và sáng tạo.', 'Ghen tị, mất tự tin, năng lượng bị thu nhỏ.'],
      ['King of Wands', 'Lãnh đạo, tầm nhìn, quyết đoán.', 'Áp đặt, hấp tấp, cần lãnh đạo chín chắn hơn.'],
    ],
  },
  {
    name: 'Cups',
    vi: 'Cốc',
    theme: 'cảm xúc, tình yêu, trực giác và kết nối',
    cards: [
      ['Ace of Cups', 'Tình cảm mới, chữa lành, trái tim mở ra.', 'Cảm xúc nghẽn lại, khó đón nhận yêu thương.'],
      ['Two of Cups', 'Kết nối đôi bên, hòa hợp, lời hứa tình cảm.', 'Lệch nhịp, hiểu lầm, cần đối thoại thật lòng.'],
      ['Three of Cups', 'Bạn bè, ăn mừng, cộng đồng nâng đỡ.', 'Quan hệ xã giao rối, cảm giác bị bỏ ngoài.'],
      ['Four of Cups', 'Chán nản, suy ngẫm, chưa thấy cơ hội trước mắt.', 'Mở lòng lại, thoát khỏi trạng thái đóng kín.'],
      ['Five of Cups', 'Tiếc nuối, mất mát, nhìn vào điều đã qua.', 'Chấp nhận, hồi phục, thấy phần còn lại.'],
      ['Six of Cups', 'Kỷ niệm, người cũ, sự dịu dàng trong quá khứ.', 'Kẹt trong hoài niệm, lý tưởng hóa chuyện cũ.'],
      ['Seven of Cups', 'Nhiều lựa chọn, mơ mộng, tưởng tượng phong phú.', 'Ảo tưởng tan, cần chọn điều thực tế.'],
      ['Eight of Cups', 'Rời đi để tìm ý nghĩa sâu hơn.', 'Sợ rời bỏ, quay lại điều không còn nuôi dưỡng mình.'],
      ['Nine of Cups', 'Ước nguyện, hài lòng, cảm xúc viên mãn.', 'Mãn nguyện hời hợt, cần hỏi điều thật sự đủ đầy.'],
      ['Ten of Cups', 'Hạnh phúc chung, gia đình, hòa hợp lâu dài.', 'Lý tưởng gia đình bị thử thách, kỳ vọng cần thực tế.'],
      ['Page of Cups', 'Tin cảm xúc, lời xin lỗi, trực giác non trẻ.', 'Nhạy cảm quá mức, cảm xúc chưa trưởng thành.'],
      ['Knight of Cups', 'Lãng mạn, lời mời, theo đuổi điều trái tim muốn.', 'Mơ mộng thiếu thực tế, lời hứa đẹp nhưng mỏng.'],
      ['Queen of Cups', 'Thấu cảm, chăm sóc, trực giác sâu.', 'Quá tải cảm xúc, cho đi đến cạn kiệt.'],
      ['King of Cups', 'Điềm tĩnh cảm xúc, bao dung, trưởng thành.', 'Kìm nén cảm xúc, kiểm soát bằng vẻ bình thản.'],
    ],
  },
  {
    name: 'Swords',
    vi: 'Kiếm',
    theme: 'suy nghĩ, sự thật, quyết định và xung đột',
    cards: [
      ['Ace of Swords', 'Sự thật rõ ràng, quyết định sắc bén, ý tưởng mới.', 'Mơ hồ, lời nói gây tổn thương, thiếu rõ ràng.'],
      ['Two of Swords', 'Bế tắc, cần chọn, tạm khóa cảm xúc.', 'Quyết định bị trì hoãn quá lâu, sự thật khó né.'],
      ['Three of Swords', 'Tổn thương, thất vọng, sự thật đau nhưng cần biết.', 'Chữa lành, buông nỗi đau cũ.'],
      ['Four of Swords', 'Nghỉ ngơi, hồi phục, tạm rút lui.', 'Không nghỉ đủ, kiệt sức tinh thần.'],
      ['Five of Swords', 'Thắng thua căng thẳng, cái giá của xung đột.', 'Buông tranh hơn thua, sửa chữa sau va chạm.'],
      ['Six of Swords', 'Rời vùng khó, chuyển sang trạng thái bình yên hơn.', 'Khó buông quá khứ, hành trình hồi phục chậm.'],
      ['Seven of Swords', 'Chiến lược, bí mật, hành động kín đáo.', 'Sự thật lộ ra, cần minh bạch hơn.'],
      ['Eight of Swords', 'Tự giới hạn, mắc kẹt trong suy nghĩ.', 'Nhìn thấy lối ra, tháo ràng buộc tinh thần.'],
      ['Nine of Swords', 'Lo âu, mất ngủ, nỗi sợ phóng đại.', 'Bắt đầu nhẹ lòng, cần nói ra điều đang sợ.'],
      ['Ten of Swords', 'Kết thúc đau, chạm đáy để sang trang.', 'Hồi phục sau kết thúc, không còn tệ hơn.'],
      ['Page of Swords', 'Quan sát, học hỏi, tin tức, câu hỏi sắc bén.', 'Hấp tấp trong lời nói, nghi ngờ quá mức.'],
      ['Knight of Swords', 'Tiến nhanh, quyết liệt, nói thẳng.', 'Vội vàng, công kích, thiếu lắng nghe.'],
      ['Queen of Swords', 'Rõ ràng, độc lập, ranh giới sắc nét.', 'Lạnh lùng, phòng vệ, phán xét quá nhanh.'],
      ['King of Swords', 'Lý trí, công bằng, quyết định có nguyên tắc.', 'Cứng rắn quá mức, dùng lý trí để áp đảo.'],
    ],
  },
  {
    name: 'Pentacles',
    vi: 'Tiền',
    theme: 'vật chất, công việc, sức khỏe và giá trị thực tế',
    cards: [
      ['Ace of Pentacles', 'Cơ hội vật chất mới, nền tảng bền vững.', 'Cơ hội bị bỏ lỡ, cần kế hoạch thực tế hơn.'],
      ['Two of Pentacles', 'Cân bằng nhiều việc, linh hoạt tài chính.', 'Quá tải, mất cân bằng, cần ưu tiên lại.'],
      ['Three of Pentacles', 'Hợp tác, tay nghề, xây dựng cùng người khác.', 'Lệch phối hợp, thiếu ghi nhận năng lực.'],
      ['Four of Pentacles', 'Giữ chặt nguồn lực, an toàn, kiểm soát tài chính.', 'Sợ mất mát, cần nới lỏng kiểm soát.'],
      ['Five of Pentacles', 'Thiếu thốn, cô đơn, giai đoạn khó khăn vật chất.', 'Tìm thấy hỗ trợ, bắt đầu phục hồi.'],
      ['Six of Pentacles', 'Cho nhận cân bằng, hỗ trợ, hào phóng.', 'Mất cân bằng quyền lực, cho nhận có điều kiện.'],
      ['Seven of Pentacles', 'Kiên nhẫn chờ thành quả, đánh giá tiến độ.', 'Nóng ruột, đầu tư chưa đúng chỗ.'],
      ['Eight of Pentacles', 'Rèn kỹ năng, chăm chỉ, nâng chất lượng.', 'Lặp lại máy móc, thiếu tập trung cải thiện.'],
      ['Nine of Pentacles', 'Độc lập, thành quả cá nhân, sự đủ đầy.', 'Phụ thuộc, chưa tin vào giá trị của mình.'],
      ['Ten of Pentacles', 'Di sản, ổn định lâu dài, gia đình/tài sản.', 'Nền tảng gia đình hoặc tài chính cần xem lại.'],
      ['Page of Pentacles', 'Học kỹ năng mới, cơ hội thực tế nhỏ nhưng quý.', 'Thiếu kỷ luật, kế hoạch học/làm chưa rõ.'],
      ['Knight of Pentacles', 'Bền bỉ, đáng tin, tiến chậm mà chắc.', 'Ì trệ, bảo thủ, quá chậm để nắm cơ hội.'],
      ['Queen of Pentacles', 'Chăm sóc thực tế, ổn định, sung túc.', 'Quên chăm mình, ôm quá nhiều trách nhiệm.'],
      ['King of Pentacles', 'Thành tựu, quản trị tài chính, sự vững vàng.', 'Tham kiểm soát, đặt vật chất lên trên mọi thứ.'],
    ],
  },
];

const minorArcana = suits.flatMap(suit =>
  suit.cards.map(([name, upright, reversed], index) => ({
    name,
    viName: `${minorRankVietnamese[index]} ${suit.vi}`,
    arcana: 'Minor Arcana',
    suit: suit.name,
    suitVi: suit.vi,
    theme: suit.theme,
    upright,
    reversed,
    image: '',
    number: index + 1,
  }))
);

const getCardImageFile = (card) => {
  if (card.arcana === 'Major Arcana') {
    const majorFileNames = [
      '00-TheFool.png',
      '01-TheMagician.png',
      '02-TheHighPriestess.png',
      '03-TheEmpress.png',
      '04-TheEmperor.png',
      '05-TheHierophant.png',
      '06-TheLovers.png',
      '07-TheChariot.png',
      '08-Strength.png',
      '09-TheHermit.png',
      '10-WheelOfFortune.png',
      '11-Justice.png',
      '12-TheHangedMan.png',
      '13-Death.png',
      '14-Temperance.png',
      '15-TheDevil.png',
      '16-TheTower.png',
      '17-TheStar.png',
      '18-TheMoon.png',
      '19-TheSun.png',
      '20-Judgement.png',
      '21-TheWorld.png',
    ];
    return majorFileNames[card.number];
  }

  return `${card.suit}${String(card.number).padStart(2, '0')}.png`;
};

export const tarotDeck = [...majorArcana.map(([name, upright, reversed], index) => ({
  name,
  viName: majorVietnameseNames[index],
  arcana: 'Major Arcana',
  suit: 'Major',
  suitVi: 'Ẩn chính',
  theme: 'bài học linh hồn, bước ngoặt lớn và năng lượng chủ đạo',
  upright,
  reversed,
  image: '',
  number: index,
})), ...minorArcana].map((card, index) => ({
  ...card,
  id: index + 1,
  image: new URL(`../../Cards-png/${getCardImageFile(card)}`, import.meta.url).href,
}));

export const tarotCardBack = new URL('../../Cards-png/Behind.png', import.meta.url).href;
